### ISSUE TITLE
apple - diversity - Google Sheets

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#148]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-16920-a81fdf2ca491c4acd1166df6a9c4e4a1) 

## [QUANTITATIVE PERSPECTIVES](https://www.techrepublic.com/article/5-eye-opening-statistics-about-minorities-in-tech/)

Compared to overall private industry, the high tech sector employed a 
larger share of 
1. WHITES 
    - 63.5 percent to 
    - 68.5 percent, 
2. ASIAN AMERICANS 
    - 5.8%
    - 14% and 
3. MEN
    - 52% 
    - 64%, 

AND 
`a smaller share of`

1. AFRICAN AMERICAN 
    - 14.4% to 
    - 7.4% 
2. Hispanics 
    - 13.9% to
    - 8%, and 
3. WOMEN
    - 48% to
    - 36%

> In the tech sector nationwide, whites are represented at a higher rate in the Executives category 

COLOR—LESS C-SUITES 
    - 83.3% 

> Roughly over 15 percentage points higher than their representation in the Professionals category 

PROFESSIONAL WHITES 
    - 68%, 

> which includes jobs such as computer programming. 

However, other groups are represented at significantly lower rates in the Executives category than in the Professionals category; 

AFRICAN AMERICANS
    - 2%  to 
    - 5.3%, 

HISPANICS
    - 3.1% to 
    - 5.3%, and 

ASIAN AMERICANS    - 10.6% to 
    - 19.5%

Of those in the Executives category in high tech, about 80 percent are men and 20 percent are women. Within the overall private sector, 71 percent of Executive positions are men and about 29 percent are women.

---
**Source URL**:
[https://docs.google.com/spreadsheets/d/1wQbP_f9faXGKKyWBTsKOd9yt4xqnLktvq_8AofdupSI/edit#gid=785042388](https://docs.google.com/spreadsheets/d/1wQbP_f9faXGKKyWBTsKOd9yt4xqnLktvq_8AofdupSI/edit#gid=785042388)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 84.0.4147.89</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2880x1332</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr></table>

**Comment by OUDcollective** [comment]
# CLOSED 

---

By mistake. Re-opened with a 3,650 day estimate to delivering quantifiable metrics. Stay tuned. 


Best, 


x.[________](https://github.com/oudcollective "keep ya on domain - right?")
[with Wind](https://gitbhub.com/withWind "c'mon now... care to ¿CC011aborate?")
[care to ¿CCO11aborate?](https://twitter.com/oudcollective "don't steal it - rather partner with Wind???")
