### ISSUE TITLE
Review Assertions | System for Award Management

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#153]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-16936-a91d0cfe09a48fc9ea978ed8d8e72e92) 

 ## Change Wind Will See In this World

1. Register Entity
2. Navigate Abyss
3. Establish EIN
4. Establish DUNS
5. Register at ___- dot Gov
6. Systems Upgrade move to ____ dot Gov
7. Determine NAICS 
8. Switch to dot dot dot dot Gov
9. Redundant
10. Non-cross-functional
11. Barriers and Groupthink Diseased
12. Definitively Drain US Swamp
13. Put US Under God Once More
14. Change the novel coronavirus trend
15. Find happier, healthier, whole tax-paying citizens
16. Improve the exponentially detrimental fertility rates
17. Stop printing Currency to purchase Equities
18. Find Sustainability.
19. End recidivistic horse shit
20. Eradicate earth of Big Pharma and Chemo-non-therapy politicking.
21. Ban Lobbyist and Federal Investments in Alcohol and Tobacco until such time as all Substances are not just decriminalized, legalized, and all non-violent offenders receive pardons, and stipends from victimization of a 50+ year failed war that is literally killing US from the inside out. 
22. Eradicate the two-party system and replace it with a dynamic, true democracy that alll US citizens can take place in as the time for constituents, legacies, latin gates, and sophisticated social status caste systems is long since dead.
23. End epidemic
24. Stop censorship
25. Bend curves
26. Bridge divides
27. Change color theory
28. Flip Scripts
29. Move Consciousness
30. Wipe Slates
31. Prevent one fell swoop - whoosh - from above...
32. Eradicate IT Gates ... 
33. When everyone else is in ... are you in?

Best, 

x.________
[with Wind LLC](https://www.pinterest.com/withWindllc "Popular on the categorical associative foldering space aka the 'Pinterest'")

---
**Source URL**:
[https://sam.gov/SAM/pages/secured/entity/assertionReview.jsf](https://sam.gov/SAM/pages/secured/entity/assertionReview.jsf)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.15</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560x937</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
# Hemp - Hinted 

## Forefathers + Poor Richard Did it

> Why can't - whoosh - with Wind? 

Best, 


x._________
[Care to CC-11-aborate?](https://twitter.com/oudcollective)
