### ISSUE TITLE
Indian Springs State Park : Explore Georgia 

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#231]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-17839-903a4e118e315a13fd90a0de576ed4d1) 

---

### A 2020 Travel Guide 

---
**Source URL**:
[Explore Georgia](http://trendmag2.trendoffset.com/publication/?m=53618&i=646596&p=110)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.59</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>3840x1332</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![indian-springs-state-park](https://user-images.githubusercontent.com/50818414/89964454-2a95af00-dc18-11ea-8dd2-224372af99f1.jpg)

> img optimization by sqoosh.app
