### ISSUE TITLE
Georgia Grown Peaches 

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#232]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-17840-435c0a313e3ac42010cb64442e652c49) 

### A 2020 Travel Guide

---
**Source URL**:
[http://trendmag2.trendoffset.com/publication/?m=53618&i=646596&p=112](http://trendmag2.trendoffset.com/publication/?m=53618&i=646596&p=112)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.59</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>3840x1332</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![georgia-grown-peaches](https://user-images.githubusercontent.com/50818414/89964296-c377fa80-dc17-11ea-9a20-61adcba8703c.jpg)

> img optimization by sqoosh.app
