### ISSUE TITLE
Historic High Country 

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#233]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-17841-ca37d6f997a3d0478190b2385a304a3f) 

---
**Source URL**:
[http://trendmag2.trendoffset.com/publication/?m=53618&i=646596&p=118](http://trendmag2.trendoffset.com/publication/?m=53618&i=646596&p=118)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.59</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>3840x1332</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![historic-high-country](https://user-images.githubusercontent.com/50818414/89964073-4f3d5700-dc17-11ea-9471-6448b45e097b.jpg)

> img optimization by sqoosh.app

**Comment by OUDcollective** [comment]
![historic-high-country 640width](https://user-images.githubusercontent.com/50818414/89964178-7136d980-dc17-11ea-821e-442b663d094e.jpg)

640 width
