### ISSUE TITLE
Northeast Georgia Mountains

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#237]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-17845-71d736a7901eed3d28cffd8175f51195) 

### A 2020 Travel Guide 

---
**Source URL**:
[http://trendmag2.trendoffset.com/publication/?m=53618&i=646596&p=142](http://trendmag2.trendoffset.com/publication/?m=53618&i=646596&p=142)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.59</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>3840x1332</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![northeast-georgia-mountains](https://user-images.githubusercontent.com/50818414/89963962-038aad80-dc17-11ea-9f2e-5089efbfa779.jpg)


img optimization by sqoosh.app
