### ISSUE TITLE
Quantified Self

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#256]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-17953-8f6ea61e6e2e0803d93e1ece4e5ad7ef) 

 ##  Interactive Resume 

### On 'The' [Google Drive](https://bit.ly/The-Quantified-Self-twenty-20)

---
**Source URL**:
[https://docs.google.com/spreadsheets/d/1_vlNT7ZPxL5ss03AIlRLYYWfpRNi72GzumF_oklyB8g/preview](https://docs.google.com/spreadsheets/d/1_vlNT7ZPxL5ss03AIlRLYYWfpRNi72GzumF_oklyB8g/preview)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.59</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>3840x1332</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>75%</td></tr></table>

**Comment by OUDcollective** [comment]
![heatmap-cbrennanpoole-the-Google-Drive](https://user-images.githubusercontent.com/50818414/89962792-cbce3680-dc13-11ea-919d-40a6fc8b010e.jpg)

> img optimization courtesy sqoosh.app
