### ISSUE TITLE
Epic Fail : 'The' Google & YouTube Music

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#276]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-18196-dfa61b33696a08bc8d94061fba5b7601) 

 > Just taste the soup? 

// What? Soup to hot? Soup to Cold?

> Just taste the soup. 

// Okay... Okay...Where's the spoon? 

> Ah-khaa Ah-khaa

Credits : [We Are Young (feat. Janelle Monáe) - YouTube Music](https://music.youtube.com/watch?v=f_K_0SNaRk0&list=PLzQP6g4y4msMxs_DGZfsih8k84Lp_jHCQ)
[Arsenio Hall & Eddie Murphy](https://www.youtube.com/watch?v=4_ACpcZbB04) from [Coming to America : End credits and best barber shop scene made available to the masses](https://www.youtube.com/watch?v=CKsSvR5u-qk)

Best, 

x._________
[Think.with WInd](https://crunchbase.com/organization/chasing-the-wind-llc)
🤓 #Accessibility #twenty20times #opportunity #ITgates certainly does; and this one is downright pitiful! 

---
**Source URL**:
[https://music.youtube.com/watch?v=f_K_0SNaRk0&list=PLzQP6g4y4msMxs_DGZfsih8k84Lp_jHCQ](https://music.youtube.com/watch?v=f_K_0SNaRk0&list=PLzQP6g4y4msMxs_DGZfsih8k84Lp_jHCQ)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.69</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2880x1405</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>110.00000000000001%</td></tr></table>

**Comment by OUDcollective** [comment]
Just taste the soup! 

![Just Taste the Soup](
![image](https://user-images.githubusercontent.com/50818414/90377342-e22a2700-e045-11ea-973e-6756404f0f93.png))
