### ISSUE TITLE
In-Demand Skilling

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#301]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-18520-8eac82a556aa321eb1f6e84d03fa71b3) 

 # Georgia DOL 
> Top In-demand skills with a real-time look at the power of data analytics, relational databases, and data science currently wield. 

## with Wind 
-[Casey Brennan Poole](https://oudcollective.github.io/Qualitative-Self)
- [x] Data Analysis
- [x] Mathematics
- [x] Data Management 
- [ ] Data Warehousing 
- [ ] Sales Modeling
- [x] Data Mining
- [ ]Extraction, Transformation, & Loading (ETL)
- [x] Relational Databases 
- [x] Spreadsheets 
- [x] Business Analysis
- [x] Economics 
- [ ] Validation
- [x] Business Process
- [ ] Risk Management
- [ ] Underwriting
- [ ] Database Administration
- [ ] Database Design
- [ ] Data Architecture
- [x] Accounting
Best, 

x.[_______](https://linkedin.com/company/the-wind "The LinkedIn Project") 
[with Wind](https://github.com/withWindllc "whoosh")
[+1 470-580-1515](https://hangouts.google.com/?hs=139&action=chat&pn=4705801515)
[gitactionable@chasingthewindllc.com](mailto:gitactionable@chasingthewindllc.com)
[crunchbase founder profile](https://crunchbase.com/person/c-brennan-poole)
[crunchbase with Wind](https://crunchbase.com/organization/chasing-the-wind-llc)
[Pinterest with Wind](https://pinterest.com/withWindllc/boards/)
[twitter](https://twitter.com/oudcollective/)
[my.bio](https://my.bio/thewindllc)

---
**Source URL**:
[Employ Georgia In-Demand Skills](https://www.employgeorgia.com/jobseekers/explorer/report/degreecertification/613#)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.83</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>3840x1332</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
- [x] Business Analysis
- [ ] Economics 
- [ ] Validation
- [ ] Business Process
- [ ] Risk Management
- [ ] Underwriting
- [ ] Database Administration
- [ ] Database Design
- [ ] 
- [ ]
