### ISSUE TITLE
with Wind needs : Best Buy Shopping Spree

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#335]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-18747-cfe205348e9376f2904d9b1c4dd687c2) 

 Why Not Pitch for Financial? What's the worst that could happen? 

> #FAILHUGE

`US Daily`

Best, 

cbrennanpoole

---
**Source URL**:
[https://www.bestbuy.com/cart](https://www.bestbuy.com/cart)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.83</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2880x1405</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![quantitative-definition-by-c-brennan-poole](https://user-images.githubusercontent.com/50818414/92188235-08174000-ee2a-11ea-8cab-28cfcc360607.jpg "credit: cbrennanpoole with an adobe spark assist") | 
![qualitatitve-definition-by-c-brennan-poole](https://user-images.githubusercontent.com/50818414/92188261-182f1f80-ee2a-11ea-8291-019f53f0fbd1.jpg "credit: cbrennanpoole with an adobe spark assist" )
