### ISSUE TITLE
Credit Sesame - Overview

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#337]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-18751-e0745e963ccae9b760118f64ba9b98a7) 

---
**Source URL**:
[https://secured.creditsesame.com/dashBoard](https://secured.creditsesame.com/dashBoard)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.83</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2880x1405</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![saia-inc-2013-annual-report -11-straight-quarters-improved-profitability-with-c-brennan-poole](https://user-images.githubusercontent.com/50818414/92187582-2c721d00-ee28-11ea-938d-5d2053f3c454.png) | ![saia-inc-2012-annual-report-7-straight-quarters-improved-profitability-with-c-brennan-poole](https://user-images.githubusercontent.com/50818414/92187600-3562ee80-ee28-11ea-8380-31edd2f39e83.png)
