### ISSUE TITLE
Credit Sesame - Account Mix

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#338]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-18752-0cc2b07b8e80f044f17d715d29b5cd43) 

---
**Source URL**:
[https://secured.creditsesame.com/factors/accountMix](https://secured.creditsesame.com/factors/accountMix)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 85.0.4183.83</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2880x1405</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![qualitatitve-definition-by-c-brennan-poole](https://user-images.githubusercontent.com/50818414/92187310-6393fe80-ee27-11ea-90e1-a29d4578dda2.png)
