### ISSUE TITLE
The Convergence of Wills - Google Slides

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#371]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-19170-7d877bf93963152ba86fcb991cdeda89) 

`SERP` `Hack.withWind.llc` `Select` . ` CTRL + C` (just-in-case the browser doesn't crash on you) + (with your full-body word selection of choice)   `Right-click` `Click : Search Google for ___` `SELCtrlCRtClickSERP` `Hack` `whoosh` `with Wind` 

## SUBJECT : 

```
Google, LLC 
```

## KEYWORD : 
`Bottom-up` `Phishlabs` `Phishing` `categorical-associative` `bias built-in` `algorithm whispering`    

## ISSUES : 

- The **corporatocracy** that is suffocating US. 

## [Phish Labs](https://info.phishlabs.com/contact-us "name's c brennan poole DOB : 10 May, 1983 ID : 052388052 Property of : 10016189350 and your e-crime phishing algorithm is picking up on my truly transparent, readily accessible, will make myself available, debt-free, grant-free, pandemically, asset-less; you see? And if you aren't here to discuss anything short of an opportunity, then I have a problem with the way-in-which your formula would mis-fire and affix me categorically to the list I would like to formally request being made public. Here on the GitHub. Using their analytics to find out you viewed my Resume-Hack directly from your domain. Telling me your phishing is fishy. If you didn't before, you do now see; am i right?")

# [Real-time SERP Work](https://www.google.com/search?q=You+hit+my+Github+directly+from+your+domain.+I%27d+like+to+know+what+list+and+why+exactly+you+hold+an+interest+in+my+wholly+authentic%2C+truly-transparent%2C+readily+accessible%2C+and+absolutely+am+available+%28for+hire%29%3B+if+that%27s+possible.+++Because%2C+if+not%2C+I+have+a+problem+with+your+%27list%27%2C+it+seems+your+algorithm+is+picking+up+on+the+all-way-out-there%2C+rather+than+phishing+for+fraudulence%2C+and+categorically+associating+to+the+root+of+our+pandemic+problems.+As+I+am+a+bottom-up+strategic+ops+manager.+And+it%27s+where+I+sit.+Holding+absolutely+zero+threat.+To+the+betterment+of+our+people.+On+a+global+level.+With+an+everyday+honest+attempt+at+rooting+out+my+own+unconscious+bias%2C+and+propagandized+influences+built+into+the+built-to-fail+N.+American+engineering.+++Let%27s+talk%2C+if+you%27ll+give+me+the+courtesy+that+is.+In+all+due+respect.+++Best%2C++++x._______+with+Wind+LLC+https%3A%2F%2Fbit.ly%2Foudcollective+https%3A%2F%2Flinkedin.com%2Fin%2Fc-brennan-poole+https%3A%2F%2Flinkedin.com%2Fin%2Foudcollective++%28nothing+unethical+on+this+as+LinkedIn+refused+to+help+me+in+merging%2C+so+I+took+to+iterative+A%2FB+testing%29&oq=You+hit+my+Github+directly+from+your+domain.+I%27d+like+to+know+what+list+and+why+exactly+you+hold+an+interest+in+my+wholly+authentic%2C+truly-transparent%2C+readily+accessible%2C+and+absolutely+am+available+%28for+hire%29%3B+if+that%27s+possible.+++Because%2C+if+not%2C+I+have+a+problem+with+your+%27list%27%2C+it+seems+your+algorithm+is+picking+up+on+the+all-way-out-there%2C+rather+than+phishing+for+fraudulence%2C+and+categorically+associating+to+the+root+of+our+pandemic+problems.+As+I+am+a+bottom-up+strategic+ops+manager.+And+it%27s+where+I+sit.+Holding+absolutely+zero+threat.+To+the+betterment+of+our+people.+On+a+global+level.+With+an+everyday+honest+attempt+at+rooting+out+my+own+unconscious+bias%2C+and+propagandized+influences+built+into+the+built-to-fail+N.+American+engineering.+++Let%27s+talk%2C+if+you%27ll+give+me+the+courtesy+that+is.+In+all+due+respect.+++Best%2C++++x._______+with+Wind+LLC+https%3A%2F%2Fbit.ly%2Foudcollective+https%3A%2F%2Flinkedin.com%2Fin%2Fc-brennan-poole+https%3A%2F%2Flinkedin.com%2Fin%2Foudcollective++%28nothing+unethical+on+this+as+LinkedIn+refused+to+help+me+in+merging%2C+so+I+took+to+iterative+A%2FB+testin "https://www.google.com/search?q=You+hit+my+Github+directly+from+your+domain.+I%27d+like+to+know+what+list+and+why+exactly+you+hold+an+interest+in+my+wholly+authentic%2C+truly-transparent%2C+readily+accessible%2C+and+absolutely+am+available+%28for+hire%29%3B+if+that%27s+possible.+++Because%2C+if+not%2C+I+have+a+problem+with+your+%27list%27%2C+it+seems+your+algorithm+is+picking+up+on+the+all-way-out-there%2C+rather+than+phishing+for+fraudulence%2C+and+categorically+associating+to+the+root+of+our+pandemic+problems.+As+I+am+a+bottom-up+strategic+ops+manager.+And+it%27s+where+I+sit.+Holding+absolutely+zero+threat.+To+the+betterment+of+our+people.+On+a+global+level.+With+an+everyday+honest+attempt+at+rooting+out+my+own+unconscious+bias%2C+and+propagandized+influences+built+into+the+built-to-fail+N.+American+engineering.+++Let%27s+talk%2C+if+you%27ll+give+me+the+courtesy+that+is.+In+all+due+respect.+++Best%2C++++x._______+with+Wind+LLC+https%3A%2F%2Fbit.ly%2Foudcollective+https%3A%2F%2Flinkedin.com%2Fin%2Fc-brennan-poole+https%3A%2F%2Flinkedin.com%2Fin%2Foudcollective++%28nothing+unethical+on+this+as+LinkedIn+refused+to+help+me+in+merging%2C+so+I+took+to+iterative+A%2FB+testing")

**Comment by OUDcollective** [comment]
![im-at-a-room-at-the-top-of-the](https://user-images.githubusercontent.com/50818414/93012436-6bae1580-f56e-11ea-826e-c394294db959.jpg "student to Earl.Tom Petty. That's it!")
