### ISSUE TITLE
How to bypass G-Suite

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#377]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-19243-5ebfad921c774ef67eb3f0e579e1946a) 

 # [Domains.google.com](https://domains.google.com)     
`lean` `enterprise` `growth-hacking` `IT Gates` `unsustainable rates`

---- 

1. Select Domain of choose. 
2. in side nav bar select : Email. 
    - [x] Email Forwarding.
    - [ ] For single user, using the * will allow for a wild-card and unlimited gmail addresses. 
    - [x] for multiple users, choose the name and add their individual email
3. An Example :    
![https://camo.githubusercontent.com/6ce9540b13e3d9e3494605f8548cab790b29fad2/68747470733a2f2f7777772e617765736f6d6573637265656e73686f742e636f6d2f6170692f76312f64657374696e6174696f6e2f696d6167652f73686f773f496d6167654b65793d746d2d333935372d31393234352d6630313932306530333133373335653661333930343066616135646266326637](https://camo.githubusercontent.com/6ce9540b13e3d9e3494605f8548cab790b29fad2/68747470733a2f2f7777772e617765736f6d6573637265656e73686f742e636f6d2f6170692f76312f64657374696e6174696f6e2f696d6167652f73686f773f496d6167654b65793d746d2d333935372d31393234352d6630313932306530333133373335653661333930343066616135646266326637 "copy?, hope so...")

    - [ ] Verify ownership of account with confirmation email. 

"Hey Google... What is C Brennan Poole Vision?"
![https://camo.githubusercontent.com/2f5b1b2589afe514432dd0cbdcd186f3b30b8094/68747470733a2f2f7777772e617765736f6d6573637265656e73686f742e636f6d2f6170692f76312f64657374696e6174696f6e2f696d6167652f73686f773f496d6167654b65793d746d2d333935372d31393234342d3161333462646637326337383634363236396634386530303830653439363939](https://camo.githubusercontent.com/2f5b1b2589afe514432dd0cbdcd186f3b30b8094/68747470733a2f2f7777772e617765736f6d6573637265656e73686f742e636f6d2f6170692f76312f64657374696e6174696f6e2f696d6167652f73686f773f496d6167654b65793d746d2d333935372d31393234342d3161333462646637326337383634363236396634386530303830653439363939 "Nothing, if not a `lean` `hack`...")

to close gaps, bridge divides, bend curves, & eradicate IT gates, ploughing a path (via algorithm and backend whisperings) that others can freely follow...

Best, 

x._____
[with Wind](https://withWind.llc "i think she's live")

---
**Source URL**:
[https://domains.google.com/registrar/dialgeorgia.com/email](https://domains.google.com/registrar/dialgeorgia.com/email)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 86.0.4240.30</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>3747x1465</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![memoji-wink - wink-square-with-wind](https://user-images.githubusercontent.com/50818414/93132077-0c055680-f6a3-11ea-9886-a5b084ef103c.png "all done with moji-man courtesy of : Apple Developers & Apple, Inc. Pimp feature!")

**Comment by OUDcollective** [comment]
![cbrennanpoole-winks](https://user-images.githubusercontent.com/50818414/93132162-30f9c980-f6a3-11ea-9fc0-ff0ae86a1fe8.png "png circular journey")
