### ISSUE TITLE
University and business school ranking in U.S.A.

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#38]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-16080-e62be0ecd52be92f15eb59b3fd4258c6) 

 # Business School Rankings in US

### Robinson College of Business 

> Georgia State University 

35th - ranked 4-Palmes Universal Business School with Strong International Influence 

credit : [eduniversal](https://eduniversal-ranking.com/business-school-university-ranking-in-usa.html) <br>
curation by : [c brennan poole](https://oudcollective.github.io/Quantified-Self) <br>
[with Wind LLC](https://linkedin.com/company/the-wind)<br>

---
**Source URL**:
[https://eduniversal-ranking.com/business-school-university-ranking-in-usa.html](https://eduniversal-ranking.com/business-school-university-ranking-in-usa.html)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 84.0.4147.68</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560x888</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
[business-ranking-eduniversal-with-wind-llc-a-robinson-college-of-business-entity.pdf](https://github.com/OUDcollective/Quantified-Self/files/4841875/business-ranking-eduniversal-with-wind-llc-a-robinson-college-of-business-entity.pdf)
