### ISSUE TITLE
©2021 Google LLC, used with permission. Google and the Google logo are registered trademarks of Google LLC.

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#393]
# [the Google Training Center](http://g.co/newstraining "Google News Initiative")       
`Google News Initiative` `How-to` `git actionable` `with Wind`    
----

![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-19472-4334091e4d831345ded8a209afe899f8) 

## On the [Google & Copyrights](https://www.google.com/permissions/logos-trademarks/)    
---

## Legal and trademarks

The [Trademarks List](https://www.google.com/permissions/trademark/rules/) and [Logos List](https://www.google.com/permissions/trademark/logos-list.html) set out an illustrative, non-exhaustive list of trademarks owned by Google LLC, as well as suggested generic terms for those products. 

[Brand features](https://www.google.com/permissions/trademark/brand-terms/) can be used only pursuant to these guidelines, our Terms and Conditions, and for the specific purposes for which Google has given permission. Please see our rules for proper usage.

---

## When using the Google logo:

> We ask that you put one of the following taglines at the bottom of the page etc.:
 
```

©2018 Google LLC All rights reserved. Google and the Google logo are registered trademarks of Google LLC.

```

```
 
©2018 Google LLC All rights reserved. [Insert Trademark] is a trademark of Google LLC.

```

---

## We ask that you put the following tagline beneath any image featuring a Google product screenshot or data:

 ```

©2018 Google LLC, used with permission. Google and the Google logo are registered trademarks of Google LLC.

```

---

~If you’ve found a website that uses a Google trademark inappropriately:~

~We’d like to hear about it. Report inappropriate use of a Google trademark.~

---

**Source URL**:
[Google on Copyrights](https://www.google.com/permissions/logos-trademarks/)
 
 <table><tr><td><strong>Chrome Beta, it's awful</strong></td><td>Chrome 86.0.4240.42 iterate iterate iterate</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit biggest piece of poo wind's ever known.</td></tr><tr><td><strong>Screen Size</strong></td><td>1920x1080 x 2 in Woodstock, GA</td></tr><tr><td><strong>Viewport Size</strong></td><td>2787x1380</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@0.6666666865348816x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
![Ad mob by the Google](https://lh3.googleusercontent.com/Xvks3FHW60nFwpkKy78lJjg6o8gvApgJZTWkNu4e4T_NFYYASrfoKMW8KVuaS3M2kEG5Z3kKbO8j5_R88FFVXU9g1dNcEKsJ9O_VBA)

**Comment by OUDcollective** [comment]
![Google Ads](https://lh3.googleusercontent.com/fA-VqaoH17Hx0fjKIzLhpHuwkrfeUZ1D-Wr7aW2rmXXc2XaJjNoC0mLNENigQuwXVgseLNIYYiIe9ofQliAc2O08TRPfMB-VS6C6 "Ads)    
`the` Google Ads see above.

**Comment by OUDcollective** [comment]
![Ads](https://camo.githubusercontent.com/a8fbe7fe83029e382c70d1dd2e4360a05e34bf76/68747470733a2f2f6c68332e676f6f676c6575736572636f6e74656e742e636f6d2f66412d5671616f483137487830666a4b497a4c68704875776b726665555a31442d577237615732726d5858633258614a6a4e6f43306d4c4e454e696751757758566773654c4e495959694965396f66516c694163324f3038545250664d422d5653364336 "how do y'all do this")
