### ISSUE TITLE
Seed Startup Hub

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#78]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-16417-c8850d8a3895cd4a5da4891db6fbd5e2) 

 ## HARVARD BUSINESS REVIEW AFFILIATIONS 

> offer new entries and access to things we never knew existed before.

As -with Wind- nothing surprises us anymore... NOTHING...

Best,

x._________
PLEASE LOOK TO OUR FOUNDING DOCUMENTS TONIGHT AND TAKE A MINUTE TO READ THE POWERFUL TRUTHS THAT SIT WITHIN THE PREAMBLE TO US DECLARATION OF INDEPENDENCE. ITS THE FIX. A TWO-MINUTE BLURP FIXES WHOLE EARTH 

EMPHATIC ABOUT THIS. CONVINCED WITHOUT A SHADOW OF DOUBT. 

shh! Listen... Hear it yet? You will! 

---
**Source URL**:
[https://www.seedstartuphub.com/Home/MyAccount](https://www.seedstartuphub.com/Home/MyAccount)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 84.0.4147.68</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560x888</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr></table>

**Comment by OUDcollective** [comment]
THE LINKS & MAINSTAY PLAYBOOK
- Leveraging Venture Capital
https://www.crunchbase.com/person/c-brennan-poole
https://www.crunchbase.com/organization/chasing-the-wind-llc

- with Wind & Professional Platforms
https://linkedin.com/in/oudcollective
https://linkedin.com/in/c-brennan-poole
https://linkedin.com/company/the-wind

CENTERED AROUND PINTEREST
https://www.pinterest.com/withwindllc

SNIPPET OF THE CLOSED NETWORK GROWTH LOOPS
https://my.bio/thewindllc
