### ISSUE TITLE
Traffic · OUDcollective/Quantified-Self

### ISSUE THREAD

**Issue by cbrennanpoole** [cbrennanpoole/Qualitative-Self#88]
![Screen Shot from awesomescreenshot.com](https://www.awesomescreenshot.com/api/v1/destination/image/show?ImageKey=tm-3957-16421-d70acceb253fbf10c38d4f712571e013) 

 # Git Actionable!

> Then ask yourselves 1 question??? 

When did 

'
with Wind 
`
<br>

take to full -on - digital dissemination? On the 

## Git? 

Because hear Wind tell it; we was out in front of all that 

**UNCONSCIOUS BIAS**

> Back - End has been working on addressing lately...

Am I right?

Cause if I am wrong that' totally cool.  

JUST KNOW ... YALL ARE GOING TO WANT TO SEE MY

## METADATA

and I assure you - I only get - 

`
FUN-ner
`
<br>

😉

*LinkedIn mindless newsfeeds* blame them for the self - fulfilling - if that's how you like to reason with it... 

Call me Wind. 

HECK ... Call Me C .... or Brennan... 

Hell ... y'all backend ... yall can call me an idiot even. 

Just don't sit there 
and tell me no lies... 

As you take 
to tryna call me 

😜. 

Cause I ain't. 

I IS 

`
woke - no - not a joke
`

#micdrop

---
**Source URL**:
[https://github.com/OUDcollective/Quantified-Self/graphs/traffic](https://github.com/OUDcollective/Quantified-Self/graphs/traffic)
 
 <table><tr><td><strong>Browser</strong></td><td>Chrome 84.0.4147.68</td></tr><tr><td><strong>OS</strong></td><td>Windows 10 64-bit</td></tr><tr><td><strong>Screen Size</strong></td><td>2560x1080</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560x888</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@1x</td></tr><tr><td><strong>Zoom Level</strong></td><td>150%</td></tr></table>

**Comment by OUDcollective** [comment]
## welcome to algorithm whispering 

`
with Wind-v-1.2.1
`


😁🤗
